FROM alpine:3.18

RUN apk add --no-cache nginx

# Copy your config as the main nginx.conf
COPY ./nginx/nginx.conf.template /etc/nginx/nginx.conf

# Set up log directory
RUN mkdir -p /var/log/nginx && chown -R nginx:nginx /var/log/nginx

# Expose port 80
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

